### ISSUE TITLE
Files not being generated

### ISSUE THREAD

**Issue by stevenleeg** [graygilmore/grunt-shopify-sass#12]
Not entirely sure what I'm doing wrong here. I'm using this plugin along with `grunt-shopify` to get auto-uploading. Here's my setup:

Gruntfile.js
```javascript
module.exports = function(grunt) {
    grunt.loadNpmTasks('grunt-shopify-sass');
    grunt.loadNpmTasks('grunt-shopify');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');

    grunt.initConfig({
        shopify: {
            options: {
                api_key: '[redacted]',
                password: '[redacted]',
                url: '[redacted].myshopify.com',
                theme: [redacted],
                disable_growl_notifications: false
            }
        },
        shopify_sass: {
            files: {
                'assets/theme.scss.liquid': 'styles/theme.scss'
            }
        },
        coffee: {
            compile: {
                files: {
                    'assets/script.js': ['scripts/*.coffee']
                },
            },
        },
        watch: {
            coffee: {
                files: ['scripts/*.coffee'],
                tasks: ['coffee']
            },
            shopify_sass: {
                files: ['styles/*'],
                tasks: ['shopify_sass']
            },
            shopify: {
                files: ['assets/*', 'themes/*', 'snippits/*', 'config/*', 'layout/*'],
                tasks: ['shopify'],
            },
        },
    });

    grunt.registerTask('default', ['watch']);
};
```

For some reason when I run `grunt` the `grunt-shopify` plugin runs fine (it watches files and uploads them automatically) but this plugin won't generate `assets/theme.scss.liquid` when I modify `styles/theme.scss`.

I've also tried running `grunt shopify_sass` and get this output:
```
Running "shopify_sass:files" (shopify_sass) task

Done, without errors.
```
however `assets/theme.scss.liquid` still isn't being generated.

Any ideas as to what I'm doing wrong here? Thanks in advance!

**Comment by graygilmore** [comment]
Hmmm, that seems odd. I can try to have a look at it this week. Maybe @jodyheavener or @cbmunro might have an idea, too.

**Comment by stevenleeg** [comment]
I was actually able to get it to work with this config:

```javascript
        shopify_sass: {
            theme: {
                src: 'styles/theme.scss',
                dest: 'assets/theme.scss.liquid'
            }
        },
```

Maybe the documentation should be updated to reflect this?

**Comment by jodyheavener** [comment]
I think this could be considered a bug – Grunt task targets should support either file syntax style.

**Comment by graygilmore** [comment]
@jodyheavener would love a PR :smile:

**Comment by jodyheavener** [comment]
Addressed in #13

**Comment by stevenleeg** [comment]
:beers: 

awesome stuff, thanks everyone!

**Comment by seanwash** [comment]
@graygilmore Sorry to bring this back up again, but I just ran into this same issue (when using the simple example from the docs https://github.com/graygilmore/grunt-shopify-sass#simple) and the only way I could fix it was to use @stevenleeg's original solution here https://github.com/graygilmore/grunt-shopify-sass/issues/12#issuecomment-86507437

It then dawned on me to check the version installed by NPM and it indeed installed 0.2.1 instead of 0.2.2. Would it be possible to get NPM updated at some point? Thanks!
